server:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  port: 8888

graphql:
  spqr:
    http:
      enabled: true
      endpoint: /graphql
    gui:
      enabled: true
      page-title: GraphQL Playground
      endpoint: /gui
    relay:
      connection-check-relaxed: true

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/graphql-project
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  mvc:
    converters:
      preferred-json-mapper: jackson